services:
  web:
    build: .
    entrypoint: ["sh", "/code/entry.sh"]
    volumes:
      - .:/code
    ports:
      - "${DEV_PORT}:8000"
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    restart: unless-stopped
